cmake_minimum_required(VERSION 3.10)
project(tukineko LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

find_package(Qt5 COMPONENTS Core Gui Widgets REQUIRED)

set(SOURCES
    main.cpp
    mainwindow.cpp
    java/awt/component.cpp
    java/awt/frame.cpp
    java/awt/panel.cpp
    java/awt/graphics.cpp
    java/awt/color.cpp
    java/awt/image.cpp
    java/awt/dimension.cpp
    java/awt/fontmetrics.cpp
    java/awt/menu.cpp
    java/awt/popupmenu.cpp
    java/awt/toolkit.cpp
    java/awt/mediatracker.cpp
    java/awt/event/mouseevent.cpp
    java/awt/event/mouselistener.cpp
    java/awt/event/actionevent.cpp
    java/awt/event/actionlistener.cpp
    java/awt/event/windowevent.cpp
    java/awt/event/windowadapter.cpp
    java/awt/image/memoryimagesource.cpp
    java/awt/image/pixelgrabber.cpp
    java/io/inputstream.cpp
    java/io/outputstream.cpp
    java/io/bytearrayinputstream.cpp
    java/io/bytearrayoutputstream.cpp
    java/io/fileinputstream.cpp
    java/io/fileoutputstream.cpp
    java/io/file_.cpp
    java/io/randomaccessfile.cpp
    java/lang/thread.cpp
    java/lang/runtime.cpp
    tukineko/nswindow.cpp
    tukineko/nsactionlistener.cpp
    tukineko/tukineko.cpp
    tukineko/entry/nsdata.cpp
    tukineko/entry/nstext.cpp
    tukineko/entry/nsbutton.cpp
    tukineko/entry/nscolor.cpp
    tukineko/entry/nseffect.cpp
    tukineko/entry/nsssprite.cpp
    tukineko/entry/nssselect.cpp
    tukineko/entry/nssprite.cpp
    tukineko/entry/nsshell.cpp
    tukineko/global/nsresource.cpp
    tukineko/global/nsimagecache.cpp
    tukineko/global/nstimer.cpp
    tukineko/global/nsthread.cpp
    tukineko/global/nsvaluestorage.cpp
    tukineko/global/nsimage.cpp
    tukineko/file/sarfile.cpp
    tukineko/file/sarentry.cpp
    tukineko/file/sarinputstream.cpp
    tukineko/file/nsafile.cpp
    tukineko/file/nsaentry.cpp
    tukineko/file/nsainputstream.cpp
    tukineko/parser/nsparser.cpp
    tukineko/parser/nscripter.cpp
    tukineko/parser/util.cpp
    tukineko/nsdumper/parser/nsparserimpl.cpp
    tukineko/nsdumper/fcmd/fcommand.cpp
    tukineko/nsdumper/fcmd/gamecommand.cpp
    tukineko/nsdumper/fcmd/intlimitcommand.cpp
    tukineko/nsdumper/fcmd/savenumbercommand.cpp
    tukineko/nsdumper/fecmd/addcommand.cpp
    tukineko/nsdumper/fecmd/atoicommand.cpp
    tukineko/nsdumper/fecmd/cmpcommand.cpp
    tukineko/nsdumper/fecmd/datecommand.cpp
    tukineko/nsdumper/fecmd/deccommand.cpp
    tukineko/nsdumper/fecmd/divcommand.cpp
    tukineko/nsdumper/fecmd/endcommand.cpp
    tukineko/nsdumper/fecmd/getinicommand.cpp
    tukineko/nsdumper/fecmd/getregcommand.cpp
    tukineko/nsdumper/fecmd/gosubcommand.cpp
    tukineko/nsdumper/fecmd/ifcommand.cpp
    tukineko/nsdumper/fecmd/inccommand.cpp
    tukineko/nsdumper/fecmd/itoacommand.cpp
    tukineko/nsdumper/fecmd/jmpbcommand.cpp
    tukineko/nsdumper/fecmd/jmpfcommand.cpp
    tukineko/nsdumper/fecmd/loadgamecommand.cpp
    tukineko/nsdumper/fecmd/modcommand.cpp
    tukineko/nsdumper/fecmd/movcommand.cpp
    tukineko/nsdumper/fecmd/mulcommand.cpp
    tukineko/nsdumper/fecmd/notifcommand.cpp
    tukineko/nsdumper/fecmd/returncommand.cpp
    tukineko/nsdumper/fecmd/rndcommand.cpp
    tukineko/nsdumper/fecmd/rnd2command.cpp
    tukineko/nsdumper/fecmd/savegamecommand.cpp
    tukineko/nsdumper/fecmd/savecmmand.cpp
    tukineko/nsdumper/fecmd/skipcommand.cpp
    tukineko/nsdumper/fecmd/subcommand.cpp
    tukineko/nsdumper/fecmd/timecommand.cpp
    tukineko/nsdumper/cmd/ecommand.cpp
    tukineko/nsdumper/cmd/btncommand.cpp
    tukineko/nsdumper/cmd/btndefcommand.cpp
    tukineko/nsdumper/cmd/btnwaitcommand.cpp
    tukineko/nsdumper/cmd/btnwait2command.cpp
    tukineko/nsdumper/cmd/clickcommand.cpp
    tukineko/nsdumper/cmd/clickposcommand.cpp
    tukineko/nsdumper/cmd/defineresetcommand.cpp
    tukineko/nsdumper/cmd/delaycommand.cpp
    tukineko/nsdumper/cmd/gettimercommand.cpp
    tukineko/nsdumper/cmd/inputstrcommand.cpp
    tukineko/nsdumper/cmd/lookbackflushcommand.cpp
    tukineko/nsdumper/cmd/resetcommand.cpp
    tukineko/nsdumper/cmd/resettimercommand.cpp
    tukineko/nsdumper/cmd/rmodecommand.cpp
    tukineko/nsdumper/cmd/selectcommand.cpp
    tukineko/nsdumper/cmd/selgosubcommand.cpp
    tukineko/nsdumper/cmd/selnumcommand.cpp
    tukineko/nsdumper/cmd/systemcallcommand.cpp
    tukineko/nsdumper/cmd/textspeedcommand.cpp
    tukineko/nsdumper/cmd/trapcommand.cpp
    tukineko/nsdumper/cmd/waitcommand.cpp
    tukineko/nsdumper/cmd/waittimercommand.cpp
)

set(HEADERS
    mainwindow.h
    java/awt/component.h
    java/awt/frame.h
    java/awt/panel.h
    java/awt/graphics.h
    java/awt/color.h
    java/awt/image.h
    java/awt/dimension.h
    java/awt/fontmetrics.h
    java/awt/menu.h
    java/awt/popupmenu.h
    java/awt/toolkit.h
    java/awt/mediatracker.h
    java/awt/event/mouseevent.h
    java/awt/event/mouselistener.h
    java/awt/event/actionevent.h
    java/awt/event/actionlistener.h
    java/awt/event/windowevent.h
    java/awt/event/windowadapter.h
    java/awt/image/memoryimagesource.h
    java/awt/image/pixelgrabber.h
    java/io/inputstream.h
    java/io/outputstream.h
    java/io/bytearrayinputstream.h
    java/io/bytearrayoutputstream.h
    java/io/fileinputstream.h
    java/io/fileoutputstream.h
    java/io/file_.h
    java/io/randomaccessfile.h
    java/lang/thread.h
    java/lang/runtime.h
    tukineko/nswindow.h
    tukineko/nsactionlistener.h
    tukineko/tukineko.h
    tukineko/entry/nsdata.h
    tukineko/entry/nstext.h
    tukineko/entry/nsbutton.h
    tukineko/entry/nscolor.h
    tukineko/entry/nseffect.h
    tukineko/entry/nssselect.h
    tukineko/entry/nsssprite.h
    tukineko/entry/nssselect.h
    tukineko/entry/nssprite.h
    tukineko/entry/nsshell.h
    tukineko/global/nsresource.h
    tukineko/global/nsimagecache.h
    tukineko/global/nstimer.h
    tukineko/global/nsthread.h
    tukineko/global/nsvaluestorage.h
    tukineko/global/nsimage.h
    tukineko/file/sarfile.h
    tukineko/file/sarentry.h
    tukineko/file/sarinputstream.h
    tukineko/file/nsafile.h
    tukineko/file/nsaentry.h
    tukineko/file/nsainputstream.h
    tukineko/parser/nsparser.h
    tukineko/parser/nscripter.h
    tukineko/parser/util.h
    tukineko/nsdumper/parser/nsparserimpl.h
    tukineko/nsdumper/fcmd/fcommand.h
    tukineko/nsdumper/fcmd/gamecommand.h
    tukineko/nsdumper/fcmd/intlimitcommand.h
    tukineko/nsdumper/fcmd/savenumbercommand.h
    tukineko/nsdumper/fecmd/addcommand.h
    tukineko/nsdumper/fecmd/atoicommand.h
    tukineko/nsdumper/fecmd/cmpcommand.h
    tukineko/nsdumper/fecmd/datecommand.h
    tukineko/nsdumper/fecmd/deccommand.h
    tukineko/nsdumper/fecmd/divcommand.h
    tukineko/nsdumper/fecmd/endcommand.h
    tukineko/nsdumper/fecmd/getinicommand.h
    tukineko/nsdumper/fecmd/getregcommand.h
    tukineko/nsdumper/fecmd/gosubcommand.h
    tukineko/nsdumper/fecmd/ifcommand.h
    tukineko/nsdumper/fecmd/inccommand.h
    tukineko/nsdumper/fecmd/itoacommand.h
    tukineko/nsdumper/fecmd/jmpbcommand.h
    tukineko/nsdumper/fecmd/jmpfcommand.h
    tukineko/nsdumper/fecmd/loadgamecommand.h
    tukineko/nsdumper/fecmd/modcommand.h
    tukineko/nsdumper/fecmd/movcommand.h
    tukineko/nsdumper/fecmd/mulcommand.h
    tukineko/nsdumper/fecmd/notifcommand.h
    tukineko/nsdumper/fecmd/returncommand.h
    tukineko/nsdumper/fecmd/rndcommand.h
    tukineko/nsdumper/fecmd/rnd2command.h
    tukineko/nsdumper/fecmd/savegamecommand.h
    tukineko/nsdumper/fecmd/savecmmand.h
    tukineko/nsdumper/fecmd/skipcommand.h
    tukineko/nsdumper/fecmd/subcommand.h
    tukineko/nsdumper/fecmd/timecommand.h
    tukineko/nsdumper/cmd/ecommand.h
    tukineko/nsdumper/cmd/btncommand.h
    tukineko/nsdumper/cmd/btndefcommand.h
    tukineko/nsdumper/cmd/btnwaitcommand.h
    tukineko/nsdumper/cmd/btnwait2command.h
    tukineko/nsdumper/cmd/clickcommand.h
    tukineko/nsdumper/cmd/clickposcommand.h
    tukineko/nsdumper/cmd/defineresetcommand.h
    tukineko/nsdumper/cmd/delaycommand.h
    tukineko/nsdumper/cmd/gettimercommand.h
    tukineko/nsdumper/cmd/inputstrcommand.h
    tukineko/nsdumper/cmd/lookbackflushcommand.h
    tukineko/nsdumper/cmd/resetcommand.h
    tukineko/nsdumper/cmd/resettimercommand.h
    tukineko/nsdumper/cmd/rmodecommand.h
    tukineko/nsdumper/cmd/selectcommand.h
    tukineko/nsdumper/cmd/selgosubcommand.h
    tukineko/nsdumper/cmd/selnumcommand.h
    tukineko/nsdumper/cmd/systemcallcommand.h
    tukineko/nsdumper/cmd/textspeedcommand.h
    tukineko/nsdumper/cmd/trapcommand.h
    tukineko/nsdumper/cmd/waitcommand.h
    tukineko/nsdumper/cmd/waittimercommand.h
)

add_executable(${PROJECT_NAME} ${SOURCES} ${HEADERS})

target_include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    java
    java/awt
    java/awt/event
    java/awt/image
    java/io
    java/lang
    tukineko
    tukineko/entry
    tukineko/global
    tukineko/file
    tukineko/parser
    tukineko/nsdumper
    tukineko/nsdumper/parser
    tukineko/nsdumper/fcmd
    tukineko/nsdumper/fecmd
    tukineko/nsdumper/cmd
)

target_link_libraries(${PROJECT_NAME} Qt5::Core Qt5::Gui Qt5::Widgets)

set_target_properties(${PROJECT_NAME} PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/bin
)
