QT += core gui widgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = tukineko
TEMPLATE = app

CONFIG += c++11

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
    main.cpp \
    mainwindow.cpp \
    java/awt/component.cpp \
    java/awt/frame.cpp \
    java/awt/panel.cpp \
    java/awt/graphics.cpp \
    java/awt/color.cpp \
    java/awt/image.cpp \
    java/awt/dimension.cpp \
    java/awt/fontmetrics.cpp \
    java/awt/menu.cpp \
    java/awt/popupmenu.cpp \
    java/awt/toolkit.cpp \
    java/awt/mediatracker.cpp \
    java/awt/event/mouseevent.cpp \
    java/awt/event/mouselistener.cpp \
    java/awt/event/actionevent.cpp \
    java/awt/event/actionlistener.cpp \
    java/awt/event/windowevent.cpp \
    java/awt/event/windowadapter.cpp \
    java/awt/image/memoryimagesource.cpp \
    java/awt/image/pixelgrabber.cpp \
    java/io/inputstream.cpp \
    java/io/outputstream.cpp \
    java/io/bytearrayinputstream.cpp \
    java/io/bytearrayoutputstream.cpp \
    java/io/fileinputstream.cpp \
    java/io/fileoutputstream.cpp \
    java/io/file_.cpp \
    java/io/randomaccessfile.cpp \
    java/lang/thread.cpp \
    java/lang/runtime.cpp \
    tukineko/nswindow.cpp \
    tukineko/nsactionlistener.cpp \
    tukineko/tukineko.cpp \
    tukineko/entry/nsdata.cpp \
    tukineko/entry/nstext.cpp \
    tukineko/entry/nsbutton.cpp \
    tukineko/entry/nscolor.cpp \
    tukineko/entry/nseffect.cpp \
    tukineko/entry/nsssprite.cpp \
    tukineko/entry/nssselect.cpp \
    tukineko/entry/nssprite.cpp \
    tukineko/entry/nsshell.cpp \
    tukineko/global/nsresource.cpp \
    tukineko/global/nsimagecache.cpp \
    tukineko/global/nstimer.cpp \
    tukineko/global/nsthread.cpp \
    tukineko/global/nsvaluestorage.cpp \
    tukineko/global/nsimage.cpp \
    tukineko/file/sarfile.cpp \
    tukineko/file/sarentry.cpp \
    tukineko/file/sarinputstream.cpp \
    tukineko/file/nsafile.cpp \
    tukineko/file/nsaentry.cpp \
    tukineko/file/nsainputstream.cpp \
    tukineko/parser/nscripter.cpp \
    tukineko/parser/util.cpp \
    tukineko/nsdumper/fcmd/fcommand.cpp \
    tukineko/nsdumper/fcmd/gamecommand.cpp \
    tukineko/nsdumper/fcmd/intlimitcommand.cpp \
    tukineko/nsdumper/fcmd/savenumbercommand.cpp \
    tukineko/nsdumper/fecmd/addcommand.cpp \
    tukineko/nsdumper/fecmd/atoicommand.cpp \
    tukineko/nsdumper/fecmd/cmpcommand.cpp \
    tukineko/nsdumper/fecmd/datecommand.cpp \
    tukineko/nsdumper/fecmd/deccommand.cpp \
    tukineko/nsdumper/fecmd/divcommand.cpp \
    tukineko/nsdumper/fecmd/endcommand.cpp \
    tukineko/nsdumper/fecmd/getinicommand.cpp \
    tukineko/nsdumper/fecmd/getregcommand.cpp \
    tukineko/nsdumper/fecmd/gosubcommand.cpp \
    tukineko/nsdumper/fecmd/ifcommand.cpp \
    tukineko/nsdumper/fecmd/inccommand.cpp \
    tukineko/nsdumper/fecmd/itoacommand.cpp \
    tukineko/nsdumper/fecmd/loadgamecommand.cpp \
    tukineko/nsdumper/fecmd/modcommand.cpp \
    tukineko/nsdumper/fecmd/movcommand.cpp \
    tukineko/nsdumper/fecmd/mulcommand.cpp \
    tukineko/nsdumper/fecmd/notifcommand.cpp \
    tukineko/nsdumper/fecmd/returncommand.cpp \
    tukineko/nsdumper/fecmd/rndcommand.cpp \
    tukineko/nsdumper/fecmd/rnd2command.cpp \
    tukineko/nsdumper/fecmd/savegamecommand.cpp \
    tukineko/nsdumper/fecmd/skipcommand.cpp \
    tukineko/nsdumper/fecmd/subcommand.cpp \
    tukineko/nsdumper/fecmd/timecommand.cpp \
    tukineko/nsdumper/ecmd/ecommand.cpp \
    tukineko/nsdumper/ecmd/btncommand.cpp \
    tukineko/nsdumper/ecmd/btndefcommand.cpp \
    tukineko/nsdumper/ecmd/btnwaitcommand.cpp \
    tukineko/nsdumper/ecmd/btnwait2command.cpp \
    tukineko/nsdumper/ecmd/clickcommand.cpp \
    tukineko/nsdumper/ecmd/clickposcommand.cpp \
    tukineko/nsdumper/ecmd/defineresetcommand.cpp \
    tukineko/nsdumper/ecmd/delaycommand.cpp \
    tukineko/nsdumper/ecmd/gettimercommand.cpp \
    tukineko/nsdumper/ecmd/inputstrcommand.cpp \
    tukineko/nsdumper/ecmd/lookbackflushcommand.cpp \
    tukineko/nsdumper/ecmd/resetcommand.cpp \
    tukineko/nsdumper/ecmd/resettimercommand.cpp \
    tukineko/nsdumper/ecmd/rmodecommand.cpp \
    tukineko/nsdumper/ecmd/selectcommand.cpp \
    tukineko/nsdumper/ecmd/selgosubcommand.cpp \
    tukineko/nsdumper/ecmd/selnumcommand.cpp \
    tukineko/nsdumper/ecmd/systemcallcommand.cpp \
    tukineko/nsdumper/ecmd/textspeedcommand.cpp \
    tukineko/nsdumper/ecmd/trapcommand.cpp \
    tukineko/nsdumper/ecmd/waitcommand.cpp \
    tukineko/nsdumper/ecmd/waittimercommand.cpp \
    tukineko/nsdumper/fecmd/saveoncommand.cpp \
    tukineko/nsdumper/fecmd/saveoffcommand.cpp \
    tukineko/nsdumper/fecmd/gotocommand.cpp \
    tukineko/nsdumper/secmd/secommand.cpp \
    tukineko/nsdumper/secmd/abssetcursorcommand.cpp \
    tukineko/nsdumper/secmd/setcursorcommand.cpp \
    tukineko/nsdumper/secmd/setwindowcommand.cpp \
    tukineko/nsdumper/sfcmd/arccommand.cpp \
    tukineko/nsdumper/sfcmd/bgaliacommand.cpp \
    tukineko/nsdumper/sfcmd/cdfadeoutcommand.cpp \
    tukineko/nsdumper/sfcmd/clickstrcommand.cpp \
    tukineko/nsdumper/sfcmd/clickvoicecommand.cpp \
    tukineko/nsdumper/sfcmd/defaultfontcommand.cpp \
    tukineko/nsdumper/sfcmd/defspeedcommand.cpp \
    tukineko/nsdumper/sfcmd/dsoundcommand.cpp \
    tukineko/nsdumper/sfcmd/effectblankcommand.cpp \
    tukineko/nsdumper/sfcmd/effectcommand.cpp \
    tukineko/nsdumper/sfcmd/filelogcommand.cpp \
    tukineko/nsdumper/sfcmd/globaloncommand.cpp \
    tukineko/nsdumper/sfcmd/humanzcommand.cpp \
    tukineko/nsdumper/sfcmd/killmenucommand.cpp \
    tukineko/nsdumper/sfcmd/labellogcommand.cpp \
    tukineko/nsdumper/sfcmd/lookbackbuttoncommand.cpp \
    tukineko/nsdumper/sfcmd/lookbackcolorcommand.cpp \
    tukineko/nsdumper/sfcmd/lookbackvoicecommand.cpp \
    tukineko/nsdumper/sfcmd/menuselectcolorcommand.cpp \
    tukineko/nsdumper/sfcmd/menuselectvoicecommand.cpp \
    tukineko/nsdumper/sfcmd/menusetwindowcommand.cpp \
    tukineko/nsdumper/sfcmd/nsacommand.cpp \
    tukineko/nsdumper/sfcmd/numaliascommand.cpp \
    tukineko/nsdumper/sfcmd/rlookbackcommand.cpp \
    tukineko/nsdumper/sfcmd/rmenucommand.cpp \
    tukineko/nsdumper/sfcmd/roffcommand.cpp \
    tukineko/nsdumper/sfcmd/savenamecommand.cpp \
    tukineko/nsdumper/sfcmd/selectcolorcommand.cpp \
    tukineko/nsdumper/sfcmd/selectvoicecommand.cpp \
    tukineko/nsdumper/sfcmd/sfcommand.cpp \
    tukineko/nsdumper/sfcmd/soundpressplgincommand.cpp \
    tukineko/nsdumper/sfcmd/spicommand.cpp \
    tukineko/nsdumper/sfcmd/straliascommand.cpp \
    tukineko/nsdumper/sfcmd/transmodecommand.cpp \
    tukineko/nsdumper/sfcmd/underlinecommand.cpp \
    tukineko/nsdumper/sfcmd/versionstrcommand.cpp \
    tukineko/nsdumper/vfecmd/mesboxcommand.cpp \
    tukineko/nsdumper/vfecmd/vfecommand.cpp \
    tukineko/nsdumper/sfecmd/captioncommand.cpp \
    tukineko/nsdumper/sfecmd/getversioncommand.cpp \
    tukineko/nsdumper/sfecmd/mousecursorcommand.cpp \
    tukineko/nsdumper/sfecmd/sfecommand.cpp \
    tukineko/nsdumper/sfecmd/windoweffectcommand.cpp \
    tukineko/nsdumper/vecmd/autoclickcommand.cpp \
    tukineko/nsdumper/vecmd/avicommand.cpp \
    tukineko/nsdumper/vecmd/bgcommand.cpp \
    tukineko/nsdumper/vecmd/bltcommand.cpp \
    tukineko/nsdumper/vecmd/brcommand.cpp \
    tukineko/nsdumper/vecmd/clcommand.cpp \
    tukineko/nsdumper/vecmd/cspcommand.cpp \
    tukineko/nsdumper/vecmd/dwavecommand.cpp \
    tukineko/nsdumper/vecmd/dwaveloopcommand.cpp \
    tukineko/nsdumper/vecmd/dwavestopcommand.cpp \
    tukineko/nsdumper/vecmd/erasetextwindowcommand.cpp \
    tukineko/nsdumper/vecmd/ldcommand.cpp \
    tukineko/nsdumper/vecmd/locatecommand.cpp \
    tukineko/nsdumper/vecmd/lspcommand.cpp \
    tukineko/nsdumper/vecmd/lsphcommand.cpp \
    tukineko/nsdumper/vecmd/menuclickdefcommand.cpp \
    tukineko/nsdumper/vecmd/menuclickpagecommand.cpp \
    tukineko/nsdumper/vecmd/menufullcommand.cpp \
    tukineko/nsdumper/vecmd/menuwindowcommand.cpp \
    tukineko/nsdumper/vecmd/monocrocommand.cpp \
    tukineko/nsdumper/vecmd/mp3command.cpp \
    tukineko/nsdumper/vecmd/mp3loopcommand.cpp \
    tukineko/nsdumper/vecmd/mspcommand.cpp \
    tukineko/nsdumper/vecmd/negacommand.cpp \
    tukineko/nsdumper/vecmd/ofscpycommand.cpp \
    tukineko/nsdumper/vecmd/playcommand.cpp \
    tukineko/nsdumper/vecmd/playoncecommand.cpp \
    tukineko/nsdumper/vecmd/playstopcommand.cpp \
    tukineko/nsdumper/vecmd/printcommand.cpp \
    tukineko/nsdumper/vecmd/puttextcommand.cpp \
    tukineko/nsdumper/vecmd/quakexcommand.cpp \
    tukineko/nsdumper/vecmd/quakeycommand.cpp \
    tukineko/nsdumper/vecmd/stopcommand.cpp \
    tukineko/nsdumper/vecmd/talcommand.cpp \
    tukineko/nsdumper/vecmd/textclearcommand.cpp \
    tukineko/nsdumper/vecmd/textoffcommand.cpp \
    tukineko/nsdumper/vecmd/textoncommand.cpp \
    tukineko/nsdumper/vecmd/vecommand.cpp \
    tukineko/nsdumper/vecmd/vspcommand.cpp \
    tukineko/nsdumper/vecmd/wavecommand.cpp \
    tukineko/nsdumper/vecmd/waveloopcommand.cpp \
    tukineko/nsdumper/vecmd/wavestopcommand.cpp \
    tukineko/nsdumper/parser/nsparser.cpp \
    tukineko/nsdumper/fecmd/fecommand.cpp \
    tukineko/nsdumper/fecmd/jumpbcommand.cpp \
    tukineko/nsdumper/fecmd/jumpfcommand.cpp

HEADERS += \
    mainwindow.h \
    java/awt/component.h \
    java/awt/frame.h \
    java/awt/panel.h \
    java/awt/graphics.h \
    java/awt/color.h \
    java/awt/image.h \
    java/awt/dimension.h \
    java/awt/fontmetrics.h \
    java/awt/menu.h \
    java/awt/popupmenu.h \
    java/awt/toolkit.h \
    java/awt/mediatracker.h \
    java/awt/event/mouseevent.h \
    java/awt/event/mouselistener.h \
    java/awt/event/actionevent.h \
    java/awt/event/actionlistener.h \
    java/awt/event/windowevent.h \
    java/awt/event/windowadapter.h \
    java/awt/image/memoryimagesource.h \
    java/awt/image/pixelgrabber.h \
    java/io/inputstream.h \
    java/io/outputstream.h \
    java/io/bytearrayinputstream.h \
    java/io/bytearrayoutputstream.h \
    java/io/fileinputstream.h \
    java/io/fileoutputstream.h \
    java/io/file_.h \
    java/io/randomaccessfile.h \
    java/lang/thread.h \
    java/lang/runtime.h \
    tukineko/nswindow.h \
    tukineko/nsactionlistener.h \
    tukineko/tukineko.h \
    tukineko/entry/nsdata.h \
    tukineko/entry/nstext.h \
    tukineko/entry/nsbutton.h \
    tukineko/entry/nscolor.h \
    tukineko/entry/nseffect.h \
    tukineko/entry/nssselect.h \
    tukineko/entry/nsssprite.h \
    tukineko/entry/nssprite.h \
    tukineko/entry/nsshell.h \
    tukineko/global/nsresource.h \
    tukineko/global/nsimagecache.h \
    tukineko/global/nstimer.h \
    tukineko/global/nsthread.h \
    tukineko/global/nsvaluestorage.h \
    tukineko/global/nsimage.h \
    tukineko/file/sarfile.h \
    tukineko/file/sarentry.h \
    tukineko/file/sarinputstream.h \
    tukineko/file/nsafile.h \
    tukineko/file/nsaentry.h \
    tukineko/file/nsainputstream.h \
    tukineko/parser/nscripter.h \
    tukineko/parser/util.h \
    tukineko/nsdumper/fcmd/fcommand.h \
    tukineko/nsdumper/fcmd/gamecommand.h \
    tukineko/nsdumper/fcmd/intlimitcommand.h \
    tukineko/nsdumper/fcmd/savenumbercommand.h \
    tukineko/nsdumper/fecmd/addcommand.h \
    tukineko/nsdumper/fecmd/atoicommand.h \
    tukineko/nsdumper/fecmd/cmpcommand.h \
    tukineko/nsdumper/fecmd/datecommand.h \
    tukineko/nsdumper/fecmd/deccommand.h \
    tukineko/nsdumper/fecmd/divcommand.h \
    tukineko/nsdumper/fecmd/endcommand.h \
    tukineko/nsdumper/fecmd/getinicommand.h \
    tukineko/nsdumper/fecmd/getregcommand.h \
    tukineko/nsdumper/fecmd/gosubcommand.h \
    tukineko/nsdumper/fecmd/ifcommand.h \
    tukineko/nsdumper/fecmd/inccommand.h \
    tukineko/nsdumper/fecmd/itoacommand.h \
    tukineko/nsdumper/fecmd/loadgamecommand.h \
    tukineko/nsdumper/fecmd/modcommand.h \
    tukineko/nsdumper/fecmd/movcommand.h \
    tukineko/nsdumper/fecmd/mulcommand.h \
    tukineko/nsdumper/fecmd/notifcommand.h \
    tukineko/nsdumper/fecmd/returncommand.h \
    tukineko/nsdumper/fecmd/rndcommand.h \
    tukineko/nsdumper/fecmd/rnd2command.h \
    tukineko/nsdumper/fecmd/savegamecommand.h \
    tukineko/nsdumper/fecmd/skipcommand.h \
    tukineko/nsdumper/fecmd/subcommand.h \
    tukineko/nsdumper/fecmd/timecommand.h \
    tukineko/nsdumper/ecmd/ecommand.h \
    tukineko/nsdumper/ecmd/btncommand.h \
    tukineko/nsdumper/ecmd/btndefcommand.h \
    tukineko/nsdumper/ecmd/btnwaitcommand.h \
    tukineko/nsdumper/ecmd/btnwait2command.h \
    tukineko/nsdumper/ecmd/clickcommand.h \
    tukineko/nsdumper/ecmd/clickposcommand.h \
    tukineko/nsdumper/ecmd/defineresetcommand.h \
    tukineko/nsdumper/ecmd/delaycommand.h \
    tukineko/nsdumper/ecmd/gettimercommand.h \
    tukineko/nsdumper/ecmd/inputstrcommand.h \
    tukineko/nsdumper/ecmd/lookbackflushcommand.h \
    tukineko/nsdumper/ecmd/resetcommand.h \
    tukineko/nsdumper/ecmd/resettimercommand.h \
    tukineko/nsdumper/ecmd/rmodecommand.h \
    tukineko/nsdumper/ecmd/selectcommand.h \
    tukineko/nsdumper/ecmd/selgosubcommand.h \
    tukineko/nsdumper/ecmd/selnumcommand.h \
    tukineko/nsdumper/ecmd/systemcallcommand.h \
    tukineko/nsdumper/ecmd/textspeedcommand.h \
    tukineko/nsdumper/ecmd/trapcommand.h \
    tukineko/nsdumper/ecmd/waitcommand.h \
    tukineko/nsdumper/ecmd/waittimercommand.h \
    java/io/objectinputstream.h \
    java/io/objectoutputstream.h \
    tukineko/nsdumper/fecmd/saveoncommand.h \
    tukineko/nsdumper/fecmd/saveoffcommand.h \
    tukineko/nsdumper/fecmd/gotocommand.h \
    tukineko/nsdumper/secmd/secommand.h \
    tukineko/nsdumper/secmd/abssetcursorcommand.h \
    tukineko/nsdumper/secmd/setcursorcommand.h \
    tukineko/nsdumper/secmd/setwindowcommand.h \
    tukineko/nsdumper/sfcmd/arccommand.h \
    tukineko/nsdumper/sfcmd/bgaliacommand.h \
    tukineko/nsdumper/sfcmd/cdfadeoutcommand.h \
    tukineko/nsdumper/sfcmd/clickstrcommand.h \
    tukineko/nsdumper/sfcmd/clickvoicecommand.h \
    tukineko/nsdumper/sfcmd/defaultfontcommand.h \
    tukineko/nsdumper/sfcmd/defspeedcommand.h \
    tukineko/nsdumper/sfcmd/dsoundcommand.h \
    tukineko/nsdumper/sfcmd/effectblankcommand.h \
    tukineko/nsdumper/sfcmd/effectcommand.h \
    tukineko/nsdumper/sfcmd/filelogcommand.h \
    tukineko/nsdumper/sfcmd/globaloncommand.h \
    tukineko/nsdumper/sfcmd/humanzcommand.h \
    tukineko/nsdumper/sfcmd/killmenucommand.h \
    tukineko/nsdumper/sfcmd/labellogcommand.h \
    tukineko/nsdumper/sfcmd/lookbackbuttoncommand.h \
    tukineko/nsdumper/sfcmd/lookbackcolorcommand.h \
    tukineko/nsdumper/sfcmd/lookbackvoicecommand.h \
    tukineko/nsdumper/sfcmd/menuselectcolorcommand.h \
    tukineko/nsdumper/sfcmd/menuselectvoicecommand.h \
    tukineko/nsdumper/sfcmd/menusetwindowcommand.h \
    tukineko/nsdumper/sfcmd/nsacommand.h \
    tukineko/nsdumper/sfcmd/numaliascommand.h \
    tukineko/nsdumper/sfcmd/rlookbackcommand.h \
    tukineko/nsdumper/sfcmd/rmenucommand.h \
    tukineko/nsdumper/sfcmd/roffcommand.h \
    tukineko/nsdumper/sfcmd/savenamecommand.h \
    tukineko/nsdumper/sfcmd/selectcolorcommand.h \
    tukineko/nsdumper/sfcmd/selectvoicecommand.h \
    tukineko/nsdumper/sfcmd/sfcommand.h \
    tukineko/nsdumper/sfcmd/soundpressplgincommand.h \
    tukineko/nsdumper/sfcmd/spicommand.h \
    tukineko/nsdumper/sfcmd/straliascommand.h \
    tukineko/nsdumper/sfcmd/transmodecommand.h \
    tukineko/nsdumper/sfcmd/underlinecommand.h \
    tukineko/nsdumper/sfcmd/versionstrcommand.h \
    tukineko/nsdumper/vfecmd/mesboxcommand.h \
    tukineko/nsdumper/vfecmd/vfecommand.h \
    tukineko/nsdumper/sfecmd/captioncommand.h \
    tukineko/nsdumper/sfecmd/getversioncommand.h \
    tukineko/nsdumper/sfecmd/mousecursorcommand.h \
    tukineko/nsdumper/sfecmd/sfecommand.h \
    tukineko/nsdumper/sfecmd/windoweffectcommand.h \
    tukineko/nsdumper/vecmd/autoclickcommand.h \
    tukineko/nsdumper/vecmd/avicommand.h \
    tukineko/nsdumper/vecmd/bgcommand.h \
    tukineko/nsdumper/vecmd/bltcommand.h \
    tukineko/nsdumper/vecmd/brcommand.h \
    tukineko/nsdumper/vecmd/clcommand.h \
    tukineko/nsdumper/vecmd/cspcommand.h \
    tukineko/nsdumper/vecmd/dwavecommand.h \
    tukineko/nsdumper/vecmd/dwaveloopcommand.h \
    tukineko/nsdumper/vecmd/dwavestopcommand.h \
    tukineko/nsdumper/vecmd/erasetextwindowcommand.h \
    tukineko/nsdumper/vecmd/ldcommand.h \
    tukineko/nsdumper/vecmd/locatecommand.h \
    tukineko/nsdumper/vecmd/lspcommand.h \
    tukineko/nsdumper/vecmd/lsphcommand.h \
    tukineko/nsdumper/vecmd/menuclickdefcommand.h \
    tukineko/nsdumper/vecmd/menuclickpagecommand.h \
    tukineko/nsdumper/vecmd/menufullcommand.h \
    tukineko/nsdumper/vecmd/menuwindowcommand.h \
    tukineko/nsdumper/vecmd/monocrocommand.h \
    tukineko/nsdumper/vecmd/mp3command.h \
    tukineko/nsdumper/vecmd/mp3loopcommand.h \
    tukineko/nsdumper/vecmd/mspcommand.h \
    tukineko/nsdumper/vecmd/negacommand.h \
    tukineko/nsdumper/vecmd/ofscpycommand.h \
    tukineko/nsdumper/vecmd/playcommand.h \
    tukineko/nsdumper/vecmd/playoncecommand.h \
    tukineko/nsdumper/vecmd/playstopcommand.h \
    tukineko/nsdumper/vecmd/printcommand.h \
    tukineko/nsdumper/vecmd/puttextcommand.h \
    tukineko/nsdumper/vecmd/quakexcommand.h \
    tukineko/nsdumper/vecmd/quakeycommand.h \
    tukineko/nsdumper/vecmd/stopcommand.h \
    tukineko/nsdumper/vecmd/talcommand.h \
    tukineko/nsdumper/vecmd/textclearcommand.h \
    tukineko/nsdumper/vecmd/textoffcommand.h \
    tukineko/nsdumper/vecmd/textoncommand.h \
    tukineko/nsdumper/vecmd/vecommand.h \
    tukineko/nsdumper/vecmd/vspcommand.h \
    tukineko/nsdumper/vecmd/wavecommand.h \
    tukineko/nsdumper/vecmd/waveloopcommand.h \
    tukineko/nsdumper/vecmd/wavestopcommand.h \
    tukineko/nsdumper/parser/nsparser.h \
    tukineko/nsdumper/fecmd/fecommand.h \
    tukineko/nsdumper/fecmd/jumpbcommand.h \
    tukineko/nsdumper/fecmd/jumpfcommand.h

INCLUDEPATH += . \
    java \
    java/awt \
    java/awt/event \
    java/awt/image \
    java/io \
    java/lang \
    tukineko \
    tukineko/entry \
    tukineko/global \
    tukineko/file \
    tukineko/parser \
    tukineko/nsdumper \
    tukineko/nsdumper/parser \
    tukineko/nsdumper/ecmd \
    tukineko/nsdumper/fcmd \
    tukineko/nsdumper/fecmd \
    tukineko/nsdumper/secmd \
    tukineko/nsdumper/sfcmd \
    tukineko/nsdumper/sfecmd \
    tukineko/nsdumper/vecmd \
    tukineko/nsdumper/vfecmd


DESTDIR = $$PWD/bin
OBJECTS_DIR = $$PWD/obj

DISTFILES += \
    README.md
